apiVersion: v2
name: jenkins-jcasc
description: A Helm chart for deploying a Jenkins master with JCasC on Kubernetes.
type: application
version: 0.1.0
appVersion: "lts" # The app version this chart is compatible with
icon: https://www.jenkins.io/images/logos/jenkins/jenkins.svg