apiVersion: v1
kind: Secret
metadata:
  name: vote-poll-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: vote-poll-secrets
    helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
{{- with .Values.secrets }}
{{ toYaml . | nindent 2 }}
{{- end }}
