apiVersion: v2
name: vote-poll-app
description: An umbrella Helm chart to deploy the full Vote-Poll application stack.
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: microservice
    version: "0.1.0"
    repository: "file://../microservice"
    alias: frontend
    condition: frontend.enabled
  - name: microservice
    version: "0.1.0"
    repository: "file://../microservice"
    alias: api-gateway
    condition: api-gateway.enabled
  - name: microservice
    version: "0.1.0"
    repository: "file://../microservice"
    alias: auth-service
    condition: auth-service.enabled
  - name: microservice
    version: "0.1.0"
    repository: "file://../microservice"
    alias: user-service
    condition: user-service.enabled
  - name: microservice
    version: "0.1.0"
    repository: "file://../microservice"
    alias: poll-service
    condition: poll-service.enabled
  - name: microservice
    version: "0.1.0"
    repository: "file://../microservice"
    alias: vote-service
    condition: vote-service.enabled
  - name: microservice
    version: "0.1.0"
    repository: "file://../microservice"
    alias: result-service
    condition: result-service.enabled
