apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jenkins.fullname" . }}-admin
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.admin.password }}
  jenkins-admin-password: {{ .Values.admin.password | b64enc | quote }}
  {{- else }}
  jenkins-admin-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}