apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}-agent
  labels:
    {{- include "jenkins.labels" . | nindent 4 }}
spec:
  type: {{ .Values.agentService.type }}
  ports:
    - port: {{ .Values.agentService.port }}
      targetPort: jnlp
      protocol: TCP
      name: jnlp
  selector:
    {{- include "jenkins.selectorLabels" . | nindent 4 }}